version: '3.7'
services:
  app:
    image: tomcat:latest
    ports:
      - 8080:8080
    volumes:
      - ./build/libs/WebAppLab-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/WebAppLab-1.0-SNAPSHOT.war
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: up_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
       - 3306:3306